services:
  smartctl-exporter:
    build:
      context: ./SmartmonExporter
    restart: no
    privileged: true
    volumes:
      - ./conf/settings.json:/app/settings.json:ro
      - ./data:/data
    command: /app/SmartmonExporter export